org: jeremymatos
service: fp-api-auth


provider:
  name: aws
  runtime: python3.13
  # Default memory size for functions (default: 256MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::982830027345:role/LabRole
  environment:
    USERS_TABLE: ${sls:stage}-fp-t_users

functions:
  LoginUsuario:
    handler: LoginUsuario.handler
    events:
      - http:
          path: /auth/login
          method: post
          cors: true
          integration: lambda
          # request:
          #   parameters:
          #     headers:
          #       'Content-Type': true
  CrearUsuario:
    handler: CrearUsuario.handler
    events:
      - http:
          path: /auth/signup
          method: post
          cors: true
          integration: lambda
          # request:
          #   parameters:
          #     headers:
          #       'Authorization': true
  ValidarTokenAcceso:
    handler: ValidarTokenAcceso.handler


# LAMBDA & DYNAMODB CREATION: https://github.com/jeremy-jmc/api-pelicula/blob/main/serverless.yml

# DOCUMENTACION: 
#   https://github.com/fastapi/fastapi/issues/2712
#   https://stackoverflow.com/questions/64377405/how-to-generate-swagger-documentation-for-aws-lambda-python-api

# SEGURIDAD: https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/functions/LoginUsuario?tab=code
#    Implementar un API de usuarios con token de acceso
#    Todas las API deben ser protegidas con token de acceso
