org: jeremymatos
service: fp-api-recommendations

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 256
  timeout: 60
  iam:
    role: arn:aws:iam::982830027345:role/LabRole
  environment:
    SONGS_TABLE: ${sls:stage}-fp-t_songs
    USER_REPLAYS_TABLE: ${sls:stage}-fp-t_user_replays
    # AWS_REGION: us-east-1

functions:
  GetSongs:
    handler: GetRecommendations.lambda_handler
    memorySize: 512
    package:
      include:
        - ./**  # Incluir todo el contenido del directorio
    events:
      - http:
          path: /get-recommendations
          method: post
          cors: true
          integration: lambda
# TODO: cuando agrego que el 'Authorization' header sea obligatorio, se rompe el endpoint
          # request:
          #   parameters:
          #     headers:
          #       'Authorization': true